import type { Metadata } from "next";
import "../styles/index.css";

export const metadata: Metadata = {
  title: "HAKU - tu socio estratégico",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/images/logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>{children}</body>
    </html>
  );
}
